arcface: false
batchsize: 32
checkpoint: ''
circle: false
color_jitter: false
contrast: false
cosface: false
cosine: false
data_dir: ../data
debug: false
debug_period: 100
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
grad_clip_max_norm: 50.0
ins_gamma: 32
instance: false
label_smoothing: 0.0
lifted: false
linear_num: 512
lr: 0.05
mixstyle: false
model: resnet_ibn
model_subtype: default
name: vric_unmodified
nclasses: 2811
num_workers: 3
samples_per_class: 1
save_freq: 1
sphere: false
start_epoch: 0
stride: 2
total_epoch: 20
tpu_cores: -1
train_csv_path: /home/tomass/tomass/data/VRIC/vric_train.csv
triplet: true
val_csv_path: /home/tomass/tomass/data/VRIC/vric_val.csv
warm_epoch: 3
